### ISSUE TITLE
Network initialization post-reboot takes way too long

### ISSUE THREAD

**Issue by fghaas** [hastexo/orchestration#2]
The initialization of the network configuration takes over three minutes post-reboot. That delay is unacceptable, we need to bring this down to at most one minute.

**Comment by armaan** [comment]
@fghaas Network configuration is taking about 4 minutes and it is because OSA bridges are taking time to come back up. It is by design that cloud-init-nonet upstart job blocks further boot until all 'auto' network adapters in /etc/network/interfaces (including those sourced from /etc/network/interfaces.d/*) are up. We have 9 'auto' network adapters and their initialization is the reason why network initialization post reboot is taking too much time.
